#!/usr/bin/env bash
# Displays information about subdomains

display_domain_info() {
    local domain="$1"
    local subdomain="$2"

    local default_subdomains=("www" "lb-01" "web-01" "web-02")

    if [ -z "$subdomain" ]; then
        subdomains=("${default_subdomains[@]}")
    else
        subdomains=("$subdomain")
    fi

    for s_domain in "${subdomains[@]}"; do
        dig_output=$(dig "$s_domain.$domain" +short)
        record_type="A"
        destination=""

        if [ -n "$dig_output" ]; then
            destination="$dig_output"
        fi

        echo "The subdomain $s_domain is a $record_type record and points to $destination"
    done
}
display_domain_info "$1" "$2"
