#!/usr/bin/env bash
# Installs and configures nginx on an ubuntu machine

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'

echo 'Hello World!' > /var/www/html/index.html

NGINX_CONFIG="
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;
    location / {
        try_files \$uri \$uri/ =404;
    }

    location = /redirect_me/ {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}"

echo "$NGINX_CONFIG" > /etc/nginx/sites-available/default

service nginx start
service nginx reload
