#!/usr/bin/env bash

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
service nginx start
cat <<EOF > /etc/nginx/sites-available/default
server {
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}

EOF

nginx -t
service nginx reload
