#!/usr/bin/env bash
# Generates a MySQL dump and creates a compressed archive out of it.

DATE=$(date +"%d-%m-%y")
mysqldump -u root -p"$1" --all-databases > backup.sql
tar -czvf "$DATE.tar.gz" backup.sql
