#!/usr/bin/env bash
# Configures an nginx server to listen on port 80

rm /etc/nginx/sites-enabled/default

# Configure nginx to listen on port 80 for all IPV4 IPs
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

service nginx restart
