#!/usr/bin/env bash
# This script is displaying "Best School" 10 times,
# and on the 9th iteration, it displays "Hi" on a new line.

# Initialize a counter variable
counter=0

# Use the while loop to repeat the echo command until the counter reaches 10
while [ $counter -lt 10 ]; do
    if [ $counter -eq 8 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    ((counter++))
done
