#!/usr/bin/env bash
# This script displays numbers from 1 to 20 and prints different messages based on the iteration number

# Initialize a counter variable
counter=1

# Use the while loop to repeat the echo command until the counter reaches 20
while [ $counter -le 20 ]; do
    case $counter in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
        *)
            echo $counter
            ;;
    esac
    ((counter++))
done
